services:
  db:
    image: mysql:8.4.5
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql  
      # Only for local dev - mount the SQL file for auto-import
      - ./wp-content/mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env.db
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    hostname: wordpress
    env_file:
      - .env.wordpress
    depends_on:
      - db
    restart: always
  
volumes:
  db_data:
